# Generated by Django 2.1.5 on 2019-01-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbf_id', models.IntegerField(max_length=30)),
                ('player_class', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cards',
            },
        ),
    ]
